//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursBd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToursEntities : DbContext
    {
        public ToursEntities()
            : base("name=ToursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InfoAboutTourists> InfoAboutTourists { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Tourists> Tourists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vouchers> Vouchers { get; set; }
    }
}
