//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursBd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vouchers()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int VoucherID { get; set; }
        public Nullable<int> TouristID { get; set; }
        public Nullable<int> SeasonID { get; set; }
    
        public virtual InfoAboutTourists InfoAboutTourists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
